version: '3'
services:
  blog-article-api:
    build: .
    volumes:
    - .:/app
    ports:
    - "8080:8000"
    restart: always
    links:
    - mongodb
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    - "21018:27018"